// <auto-generated />
namespace QPC.BMS.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BMS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BMS));
        
        string IMigrationMetadata.Id
        {
            get { return "201806241806446_BMS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
